### ISSUE TITLE
 Failed to execute script cleaner when runing

### ISSUE THREAD

**Issue by Goldmaster** [cfbao/google-drive-trash-cleaner#11] opened 2020-03-30 22:23 UTC
Traceback (most recent call last):
  File "cleaner.py", line 433, in <module>
  File "cleaner.py", line 81, in main
  File "cleaner.py", line 301, in delete_old_files
  File "cleaner.py", line 410, in execute_request
  File "cleaner.py", line 404, in execute_request
  File "site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
  File "site-packages\googleapiclient\http.py", line 844, in execute
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1bLQvEgBvcNyCw7qB-_ZvZ95-njykaKwr? returned "File not found: 1bLQvEgBvcNyCw7qB-_ZvZ95-njykaKwr.">
[20164] Failed to execute script cleaner

by the looks of it's because of "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."

**Comment by cfbao** [comment] 2020-03-31 03:06
The error message you posted suggests this is a duplicate of #10.

Where did you get the "daily limit exceeded" message?

**Comment by TheGoldmasterCorporation** [comment] 2020-03-31 10:24
> Where did you get the "daily limit exceeded" message?

here sorry,

https://www.googleapis.com/drive/v3/files/1bLQvEgBvcNyCw7qB-_ZvZ95-njykaKwr

**Comment by Gvatgor** [comment] 2020-03-31 10:30
I have it too


TeamGoldmaster <notifications@github.com> | TeamGoldmaster <notifications@github.com> | 13:25 (4 минуты назад) 
 
TeamGoldmaster <notifications@github.com>
кому: cfbao/google-drive-trash-cleaner, Subscribed | кому: cfbao/google-drive-trash-cleaner, Subscribed
кому: cfbao/google-drive-trash-cleaner, Subscribed

{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}

**Comment by Gvatgor** [comment] 2020-03-31 10:30
TeamGoldmaster <notifications@github.com> | TeamGoldmaster <notifications@github.com> | 01:23 (12 часов назад) |   |  
-- | -- | -- | -- | --
TeamGoldmaster <notifications@github.com>
кому: cfbao/google-drive-trash-cleaner, Subscribed | кому: cfbao/google-drive-trash-cleaner, Subscribed
кому: cfbao/google-drive-trash-cleaner, Subscribed

**Comment by Gvatgor** [comment] 2020-03-31 10:31
Traceback (most recent call last):
File "cleaner.py", line 433, in
File "cleaner.py", line 81, in main
File "cleaner.py", line 301, in delete_old_files
File "cleaner.py", line 410, in execute_request
File "cleaner.py", line 404, in execute_request
File "site-packages\oauth2client_helpers.py", line 133, in positional_wrapper
File "site-packages\googleapiclient\http.py", line 844, in execute
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1bLQvEgBvcNyCw7qB-_ZvZ95-njykaKwr? returned "File not found: 1bLQvEgBvcNyCw7qB-_ZvZ95-njykaKwr.">
[20164] Failed to execute script cleaner

by the looks of it's because of "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup

**Comment by TheGoldmasterCorporation** [comment] 2020-03-31 10:36
ok think it might be a duplicate of #10 as when it 1st happened, I deleted the credentials file and relogged in, but did come up with a warning about less secure apps on the google sign in webpage. I'm sure its beacuse Google is trying to limit access for less secure apps. it does run but can't go through and delete every trashed file after 30 days.

i have managed to set up the program to run at startup using the --auto option as it runs in the background.

**Comment by cfbao** [comment] 2020-03-31 15:16
I'm aware of the unverified app limit. I didn't realize my script was this close to the limit.
Guess I'll have to get it verified soon.

**Comment by cfbao** [comment] 2020-10-05 03:31
Project deprecated. See [ReadMe](https://github.com/cfbao/google-drive-trash-cleaner/blob/master/README.md).

**Closed by cfbao** 2020-10-05 03:31 UTC
